title: Zero2Neuro
description: A no-code toolkit for performing deep learning experiments
remote_theme: just-the-docs/just-the-docs
url: "https://Symbiotic-Computing-Laboratory.github.io"
baseurl: ""
search_enabled: true
heading_anchors: true
color_scheme: light
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: default
