title: Zero2Neuro
description: A no-code solution to performing deep learning experiments
theme: just-the-docs

url: "Symbiotic-Computing-Laboratory@github.io"
baseurl: "/zero2neuro"

search_enabled: true
heading_anchors: true
color_scheme: light
