name: Deploy Docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll
	run: bundle install
        #run: gem install jekyll just-the-docs jekyll-remote-theme

      - name: Set deploy folder and baseurl
        id: folder
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "folder=stable" >> $GITHUB_OUTPUT
            echo "baseurl=/zero2neuro/stable" >> $GITHUB_OUTPUT
          else
            echo "folder=dev" >> $GITHUB_OUTPUT
            echo "baseurl=/zero2neuro/dev" >> $GITHUB_OUTPUT
          fi

      - name: Build Jekyll site
        run: |
	# jekyll build --destination ./_site --baseurl "${{ steps.folder.outputs.baseurl }}"
          bundle exec jekyll build --destination ./_site --baseurl "${{ steps.folder.outputs.baseurl }}"
        env:
          JEKYLL_ENV: production

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: ${{ steps.folder.outputs.folder }}
          keep_files: true
